ktor:
    application:
        modules:
            - com.nexus.gateway.ApplicationKt.module
    deployment:
        port: 8080
    jwt:
      secret: $JWT_SECRET
      issuer: "nexus-gateway"
      audience: "nexus-clients"
      realm: "Nexus Gateway API"
